name: Trigger API Autorization

on:
  schedule:
    - cron: '45 17 * * *'

jobs:
  ejecuta-ruta:
    if: github.event.schedule == '24 17 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API without waiting
        run: |
          curl -X POST -m 1 -s -o /dev/null "https://api-sistemacontable.sangregorio.edu.ec/api/v1/usgp/service/externo/cxc_estudiantes_periodo/1313762773/072/g" &
